name: Manage Secrets

on:
  workflow_dispatch:
  push:
    paths:
      - '.env.example'
      - 'wrangler.toml'

jobs:
  update-secrets:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Update GitHub Secrets
        uses: gliech/create-github-secret-action@v1
        with:
          name: 'AWS_ACCESS_KEY_ID'
          value: ${{ secrets.AWS_ACCESS_KEY_ID }}
          pa_token: ${{ secrets.GH_PA_TOKEN }}

      - name: Update Cloudflare Secrets
        run: |
          # Update D1 Database secrets
          wrangler secret put D1_DATABASE_ID --env production
          # Update KV namespace secrets
          wrangler secret put KV_NAMESPACE_ID --env production
          # Update R2 bucket secrets
          wrangler secret put R2_BUCKET_NAME --env production

      - name: Validate Configuration
        run: |
          wrangler config validate
          aws sts get-caller-identity

      - name: Notify on Success
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Secrets have been successfully updated'
            })